# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 08:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('caller_name', models.CharField(max_length=500)),
                ('caller_number', models.IntegerField(default=0)),
                ('date_reported', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(max_length=1000)),
                ('action_taken', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField(default=0)),
                ('email_address', models.EmailField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('longitude', models.CharField(default=36.8167, max_length=1000)),
                ('latitude', models.CharField(default=-1.2833, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Data_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('mortality', models.IntegerField(default=0)),
                ('remarks', models.TextField(max_length=1000)),
                ('county', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overview.County')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.Data_source')),
            ],
        ),
        migrations.CreateModel(
            name='Disease_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DSRU_Weekly_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=500)),
                ('province', models.CharField(max_length=500)),
                ('wk_no', models.IntegerField(default=0)),
                ('wn_end', models.DateField(default=datetime.date.today)),
                ('cases_under_5', models.IntegerField(default=0)),
                ('cases_over_5', models.IntegerField(default=0)),
                ('total_cases', models.IntegerField(default=0)),
                ('death_under_5', models.IntegerField(default=0)),
                ('death_over_5', models.IntegerField(default=0)),
                ('total_death', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2000)),
                ('reported', models.DateField(default=datetime.date.today)),
                ('designation', models.CharField(max_length=500)),
                ('date_reported', models.DateField(default=datetime.date.today)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.County')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.Disease_type')),
            ],
        ),
        migrations.CreateModel(
            name='EOC_Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=500)),
                ('designation', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='overview.Designation')),
            ],
        ),
        migrations.CreateModel(
            name='EOC_Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('week_no', models.CharField(max_length=50)),
                ('officer_name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='overview.EOC_Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('mortality', models.IntegerField(default=0)),
                ('remarks', models.TextField(max_length=1000)),
                ('county', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overview.County')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.Data_source')),
            ],
        ),
        migrations.CreateModel(
            name='Event_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfl_code', models.CharField(max_length=1000)),
                ('facility_name', models.CharField(max_length=1000)),
                ('facility_level', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=1000)),
                ('longitude', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Incident_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Media_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Police_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(max_length=1000)),
                ('post_name', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=1000)),
                ('longitude', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Referal_labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referal_code', models.CharField(max_length=1000)),
                ('referal_name', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=1000)),
                ('longitude', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RRT_Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('week_no', models.CharField(max_length=50)),
                ('officer_name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='overview.EOC_Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Significant_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_county',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcounty', models.CharField(max_length=1000)),
                ('longitude', models.CharField(default=36.8167, max_length=1000)),
                ('latitude', models.CharField(default=-1.2833, max_length=1000)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.County')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.Event_type'),
        ),
        migrations.AddField(
            model_name='event',
            name='incident_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overview.Incident_status'),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.Region'),
        ),
        migrations.AddField(
            model_name='event',
            name='subcounty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overview.Sub_county'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disease',
            name='disease_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.Disease_type'),
        ),
        migrations.AddField(
            model_name='disease',
            name='incident_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overview.Incident_status'),
        ),
        migrations.AddField(
            model_name='disease',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.Region'),
        ),
        migrations.AddField(
            model_name='disease',
            name='subcounty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overview.Sub_county'),
        ),
        migrations.AddField(
            model_name='disease',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='overview.Contact_type'),
        ),
        migrations.AddField(
            model_name='contact',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.County'),
        ),
        migrations.AddField(
            model_name='call_log',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overview.County'),
        ),
        migrations.AddField(
            model_name='call_log',
            name='disease_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='overview.Disease_type'),
        ),
        migrations.AddField(
            model_name='call_log',
            name='event_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='overview.Event_type'),
        ),
        migrations.AddField(
            model_name='call_log',
            name='incident_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overview.Incident_status'),
        ),
        migrations.AddField(
            model_name='call_log',
            name='subcounty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overview.Sub_county'),
        ),
        migrations.AddField(
            model_name='call_log',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
