# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_mytimetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call_log',
            options={'ordering': ['-date_reported']},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='disease',
            name='cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disease',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
    ]
