from django.contrib import admin
from .models import *

admin.site.register(Event)
admin.site.register(County)
admin.site.register(Data_source)
admin.site.register(Event_type)
admin.site.register(Call_log)
admin.site.register(Region)
admin.site.register(Disease_type)
admin.site.register(Disease)
admin.site.register(EOC_Shifts)
admin.site.register(RRT_Shifts)
admin.site.register(EOC_Contacts)
admin.site.register(Designation)
admin.site.register(DSRU_Weekly_Event)
admin.site.register(Contact_type)
admin.site.register(Contact)
admin.site.register(Incident_status)
admin.site.register(coordinates)
admin.site.register(Sub_county)
admin.site.register(Facilities)
admin.site.register(Police_posts)
admin.site.register(Referal_labs)
admin.site.register(mytimetable)
